notifications:
  email: false

# if: tag IS present

matrix:
  include:

  # manylinux1 builds
  - name: manylinux1_x86_64
    services:
      - docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - name: manylinux1_i686
    services:
      - docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686

  # manylinux2010 builds
  - name: manylinux2010_x86_64
    services:
      - docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - name: manylinux2010_i686
    services:
      - docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686

  # manylinux2014 builds
  - name: manylinux2014_x86_64
    services:
      - docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
  - name: manylinux2014_i686
    services:
      - docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io -w /io/pydave $DOCKER_IMAGE /io/pydave/build-wheels.sh
  - ls pydave/wheelhouse/
