notifications:
  email: false

# if: tag IS present

os: linux
language: minimal
python: "3"
services:
  - docker

env:
  global:
    - TWINE_USERNAME=__token__
    - secure: "sYp0SMQHqIi20tf400zAIsFLjIc/XhI5CgNJ2PrwnpGUtjCFL8nSZYPmCc2pdoFhQOMJJFDR0NXJzf+uic9he/pEfTHjRytfpldmssN56wegplIS8CgNzO/s803/XHpr/rnRimGO6EFoWzwgUvzSXeEfbW8CgZKct8AXRtZr3O5ses8D416iVcJDK65uaRpnrtwbV1HlyGmqx66bAWRoCPfxszG864iTw1cSjcNnFroLCkfxrD7CQJd/FxwJ6mAGtmcdVZc3vtui5oqv6N5o+AOM9WCMyGRbIi1qncZy16P5l3Zkgy4flpi6FYKs/jXJcb4gnfrfW7mu2vOGYDqG4G1pxluj09cMkv/CcrHTVils24DM3HAij8Jx0VsMM2NdytC+2schRVARpvJR333jao5inAobEJTjpnEnlKtovHmTXDQHiDae2zrtgFBHZmiBUXlzKFqyTuClkB0/4VlpLBEpn41B4i/xIYS4lsYpyFuASfbLLhGx+XKDXJwae9Xo3/hvn08eOCTazeO/hx8YMrmMijH5PU9Ajtnva+dTQsGDX/XX8JexEUXBJok99+8VVVw1CpfaOygVUDzF8xrQdHG8WM6CIZJ3VnEkRrFvh/sh3EvNKGjdO/WfEKZRywMIaLHmY1zVJ0Nr0GWkgFSPWCU8sYXNRMF+2u8V0NmeG8s="
  jobs:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686

install:
  - pip install twine
  - docker pull $DOCKER_IMAGE
script:
  - which -a pip pip3 python python3
  - echo "Current working directory:" $PWD
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io -w /io/pydave $DOCKER_IMAGE /io/pydave/build-wheels.sh
  - ls pydave/wheelhouse/
  - ./pydave/twine-upload.sh

jobs:
  include:
    - name: MacOS build
      os: osx
      language: minimal
      python: "3"
      env:
        -
      install:
        - pip3 install delocate twine
        - ln -f -s $(which python3) $(which python) # force re-link python to python3
      script:
        - which -a pip pip3 python python3
        - cd pydave; echo "Current working directory:" $PWD;
        - ./build-wheels.sh
        - ls wheelhouse/
        - ./twine-upload.sh
