notifications:
  email: false

# if: tag IS present

os: linux
language: minimal
services:
  - docker

env:
  global:
    # SOMEVAR
    - secure: "XSBoKB4jZ49CB2dQXdrYWnojMhbl5Cgu6mZIt6pPPZVpyd0E6gFGVdqoQZh6/8DB1F32zJdNyhoKp+L674FwcBhD0NNYAZerATCf5/v8M2gC+3K0EJRXs6TT1cXvqePlRQm5P3T+KQ09AeeJmfL1X1TuQolkjmFzvjM0wEl+qqMB5h7zC6/HM0SbfTMYz6lUfjVY3G5ACXEmbDEIVZ+f/3P+mDMXE0QI5Jd0HMwe9jAC3MgwpKrXJl5Vrw/1+L7S7lNOT/jFKgv0shLx1lKaAS8rLCX+hAMUUtpD0NT33QVWm1DuVDPTe0txjVOyYVv+Db1hZ4dtY34YimwkckUf2q5h3ghLfXExZ+YSNfl2FC6pgiKOzZO/2zU5ZrOam5RT+yZZPTnrhic7r+l68UwXw76BmuIoEXmLZdptko4Eq6Y9HOHwiP0iCicBovekaMtsGRj1DF6CM1h6DGgzeaR0j1q/vHjvSAwS7hkp7vtPBKWJYU3lugj2LJ0sqdi9gIKOfw8gPjLm9/0Nx80VjHk+vf3k1qVEwod+mos2CLYg4VryE9/vRZ/ZZYIOrB7SZ0TsSSrhjweaNxLvo0iJ9yQyRMjSR8zbdlMnY2oGbTeju19R4myU8D233rVPqt8epNtpuo609XbwqfcOJbi726ir0jlonsAx9GCbCl3NVIBbaJY="
  jobs:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686

install:
  - docker pull $DOCKER_IMAGE
script:
  - echo "Current working directory:" $PWD
  - ./pydave/twine-upload.sh
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io -w /io/pydave $DOCKER_IMAGE /io/pydave/build-wheels.sh
  - ls pydave/wheelhouse/

jobs:
  include:
    - name: MacOS build
      os: osx
      language: minimal
      env:
        -
      install:
        - pip3 install delocate
        - ln -f -s $(which python3) $(which python) # force re-link python to python3
      script:
        - cd pydave; echo "Current working directory:" $PWD;
        - ./twine-upload.sh
        - ./build-wheels.sh
        - ls wheelhouse/
