notifications:
  email: false
# if: tag IS present
matrix:
  include:
  - name: manylinux1_x86_64
    services:
      - docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - name: manylinux1_i686
    services:
      - docker
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
      - PRE_CMD=linux32
install:
  - docker pull $DOCKER_IMAGE
script:
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io -w /io/pydave $DOCKER_IMAGE /io/pydave/build-wheels.sh
  - ls pydave/wheelhouse/
