notifications:
  email: false

Authorization: token

# if: tag IS present

os: linux
language: minimal
services:
  - docker

env:
  global:
    # SOMEVAR
    - secure: "SvMOErPEkR9FLtTZZH1fy0pUTnqxyzL7TR9gi8+xpKsUJtW9/lgIkQ+pmo8uS1nWLWPULowgO6TzVPh0OWxIZ/0HANfhDTXQzIesKtUDZA2v/PT93snNkJIPrIZZJJ9RzmNdWoiDgT0OAGqOIVjCKDl/um1T+2pKqxL8KQN7dcKbfoipJOV21XPkJqmmX2aMCAKISyJeq/hIl+rddF4II5t8e4u+6945LDKk6Z834t8Yta8Pl7MR+H1tTWzAf0sPuS1Czj+FZ7is7pnEdSAkKm2X8tQuNQ9xdKDhvPvqR2+Q7mLx1KU0TnzDF9E1G0uuX9xGFqJWKabL86h50GSDJoguhsIM6dsQpsTFo/lIIKenfPpK5I4DZp4QVb71Pda0JBabXlJ7+7qJ8TPaOXc6g3TNCjnGfRHfo/cqraKtFnWpd4sOPy351vAjDRu6WXSct/n0xcr6gJXyEiseZldo66Yrr5kPMEj8LiOL3eJrsSCTOeNofRY2oyStkDCVbrkg/ST6bQKSmCadf5KaySYScyhD84Ufj8YDjI82p370gskaITOKlVqzJ4RGdT90rktZbT1gbih9UY99o5zBs+abAWBQ3TCxu+v3vztTtg6QmWgOK6iHnoN6ZNjXm7s+c8nf6+c6D2ZBtlrE5HYnDCkW/efhVy7pESmmmrsBlRknja0="
  jobs:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686

install:
  - docker pull $DOCKER_IMAGE
script:
  - echo "Current working directory:" $PWD
  - ./pydave/twine-upload.sh
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io -w /io/pydave $DOCKER_IMAGE /io/pydave/build-wheels.sh
  - ls pydave/wheelhouse/

jobs:
  include:
    - name: MacOS build
      os: osx
      language: minimal
      env:
        -
      install:
        - pip3 install delocate
        - ln -f -s $(which python3) $(which python) # force re-link python to python3
      script:
        - cd pydave; echo "Current working directory:" $PWD;
        - ./twine-upload.sh
        - ./build-wheels.sh
        - ls wheelhouse/
