notifications:
  email: false

# if: tag IS present

dist: bionic
language: python
python: "3.6"
services: docker

env:
  global:
    - TWINE_USERNAME=__token__
    - secure: "CQcODMtFcHGa9lXEGcDXomxzoB1oyxfiP+7Of2d5G5rrQaHy1Op4L0b7CJmS1LbxBBDqqe6xG+Cnn6BIDHp3HzMaWpZNHjmLyVS2QwJb5vyJhcVKb5lyUjdbIuoUOhoi+nsl1uGYR6nmRAyvElp6YOWD23Qz3OfSucgbQhUFeaHzye4WJXO5RJ1LNrTrUIkUa8UziOwTJCK2uZci94THUhNeLQzGcjOHAYkBsvBEsvPj8Vap1pQNy4A+PdXDZCwdJbpmdrrg/VXfWsFQV83dnvpZtvzCvTWVAMiPjt6Wv/eSO+ks4PShN2N2J2oXwVs0hAksyP21ZoaAHHdnNGnGDChVTcwcdn1Ts5/pNNSUX/f/jkR4aohRzBXhL/OuBbdahPbtiK4YfBunWslIOpSTh0tunMcKxB+tt9S0X7WSmo0+gPbuRM9/3S+58mlAbTfhBYv3a3mexfrcmWn7p4/8i/gW0NC9TqoiEbwzrG9e/Hz2o0UXd0h/TVpoxUXwT06DRnmAkak+iD27PJaOSJnAbKMY2vMGuuTDx3kulApLM5GQIOB1ny3H/bfYVLszD3ghf+YHzUsllfUvnh8Q6tcZr3UbBh1xNVLGPY1Rndbnq+iPeVcGlVqURhwevNJYg6/NF4p21zYHaEGhf06FuDCz664H9kk4f5TgK7YxUbbjv3c="
  jobs:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686

install:
  - pip install twine
  - docker pull $DOCKER_IMAGE
script:
  - echo "Current working directory:" $PWD
  - docker run --rm -e MANYLINUX=yes -v `pwd`:/io -w /io/pydave $DOCKER_IMAGE /io/pydave/build-wheels.sh
  - cd pydave; ls wheelhouse/
  - ./twine-upload.sh

jobs:
  include:
    - name: MacOS build
      os: osx
      language: minimal
      services:
        -
      env:
        -
      install:
        - pip3 install delocate twine
        - ln -f -s $(which python3) $(which python) # force re-link python to python3
      script:
        - cd pydave; echo "Current working directory:" $PWD;
        - ./build-wheels.sh
        - ls wheelhouse/
        - ./twine-upload.sh
