name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install openstack client
      run: sudo snap install openstackclients --classic
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2
    - name: Testing if if works
      if: github.event_name == 'push' && contains(github.ref, 'release')
      run: echo ${{ github.ref }}
